version: '3.8'

services:
  postgres:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  redis:
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  url-service:
    environment:
      - DATABASE_URL=postgresql://username:${POSTGRES_PASSWORD}@postgres:5432/url_shortener_db
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - ENVIRONMENT=production
    volumes: []  # Remove development volume mounts
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  analytics-service:
    environment:
      - DATABASE_URL=postgresql://username:${POSTGRES_PASSWORD}@postgres:5432/url_shortener_db
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/1
      - ENVIRONMENT=production
    volumes: []
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  api-gateway:
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - API_KEY=${API_KEY}
      - RATE_LIMIT_PER_MINUTE=60
      - ENVIRONMENT=production
    volumes: []
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  frontend:
    environment:
      - API_BASE_URL=http://api-gateway:8000
      - STREAMLIT_SERVER_HEADLESS=true
    volumes: []
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  nginx:
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

volumes:
  postgres_prod_data:
    driver: local